const a = [
    {
        "id": 870389177,
        "node_id": "PRR_kwDOGhRBJM4z4RW5",
        "user": {
            "login": "github-actions[bot]",
            "id": 41898282,
            "node_id": "MDM6Qm90NDE4OTgyODI=",
            "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/github-actions%5Bbot%5D",
            "html_url": "https://github.com/apps/github-actions",
            "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
            "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
            "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
            "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
            "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
            "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
            "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
            "type": "Bot",
            "site_admin": false
        },
        "body": "Please update .betterer.results",
        "state": "CHANGES_REQUESTED",
        "html_url": "https://github.com/Evilweed/chatops-pr/pull/50#pullrequestreview-870389177",
        "pull_request_url": "https://api.github.com/repos/Evilweed/chatops-pr/pulls/50",
        "author_association": "NONE",
        "_links": {
            "html": {"href": "https://github.com/Evilweed/chatops-pr/pull/50#pullrequestreview-870389177"},
            "pull_request": {"href": "https://api.github.com/repos/Evilweed/chatops-pr/pulls/50"}
        },
        "submitted_at": "2022-02-02T11:08:51Z",
        "commit_id": "cb9c35f6c170472b94732181bd7742463d051eca"
    }, {
        "id": 870733659,
        "node_id": "PRR_kwDOGhRBJM4z5ldb",
        "user": {
            "login": "github-actions[bot]",
            "id": 41898282,
            "node_id": "MDM6Qm90NDE4OTgyODI=",
            "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/github-actions%5Bbot%5D",
            "html_url": "https://github.com/apps/github-actions",
            "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
            "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
            "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
            "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
            "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
            "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
            "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
            "type": "Bot",
            "site_admin": false
        },
        "body": "### 🤖 BOT: I've detected TypeScript quality changes!\r\nCI job that compiles this project with \"strict'er\" compilation detected changes. You have either fixed some TypeScript issues, or added new. You need to review those changes and either fix new TS issues, or accept new changes as \"ok\" which will store this state in file in repo.\r\n\r\n| Project | \r\n| ---- |\r\n| platform |\r\n\r\n| Action | When to do it | What, or details | \r\n| ---- | ----- | ----- |\r\n| 1. See detailed report | Now | Open this [🔗 link to ci job](https://github.com/Evilweed/chatops-pr/runs/code-quality-check?check_suite_focus=true) and check if there are some new TS errors you can fix. You can decide not to fix those issues - but keep in mind that we are trying to improve TS practices. |\r\n| 2. Fix detected issues | The sooner the better :) | Use information from previous step to find TS errors and commit fixes. |\r\n| 3. Update `.betterer.results` file | Before merge at most | Open this [🔗 link to ci job](https://github.com/Evilweed/chatops-pr/runs/code-quality-check?check_suite_focus=true) and read instruction on how to update `.betterer.results` file |\r\n",
        "state": "DISMISSED",
        "html_url": "https://github.com/Evilweed/chatops-pr/pull/50#pullrequestreview-870733659",
        "pull_request_url": "https://api.github.com/repos/Evilweed/chatops-pr/pulls/50",
        "author_association": "NONE",
        "_links": {
            "html": {"href": "https://github.com/Evilweed/chatops-pr/pull/50#pullrequestreview-870733659"},
            "pull_request": {"href": "https://api.github.com/repos/Evilweed/chatops-pr/pulls/50"}
        },
        "submitted_at": "2022-02-02T15:42:57Z",
        "commit_id": "33111957ca3c6fd8d005335e49e5d166e809ca9b"
    }, {
        "id": 870824635,
        "node_id": "PRR_kwDOGhRBJM4z57q7",
        "user": {
            "login": "github-actions[bot]",
            "id": 41898282,
            "node_id": "MDM6Qm90NDE4OTgyODI=",
            "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/github-actions%5Bbot%5D",
            "html_url": "https://github.com/apps/github-actions",
            "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
            "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
            "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
            "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
            "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
            "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
            "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
            "type": "Bot",
            "site_admin": false
        },
        "body": "### 🤖 BOT: I\\'ve detected TypeScript quality changes!\nCI job that compiles this project with strict'er compilation detected changes. You have either fixed some TypeScript issues, or added new. You need to review those changes and either fix new TS issues, or accept new changes as ok which will store this state in file in repo.\n \n| Project |\n| ---- |\n| platform |\n \n| Action | When to do it | What, or details |\n| ---- | ----- | ----- |\n| 1. See detailed report | Now | Open this [🔗 link to ci job](https://github.com/Evilweed/chatops-pr/runs/?check_suite_focus=true) and check if there are some new TS errors you can fix. You can decide not to fix those issues - but keep in mind that we are trying to improve TS practices. |\n| 2. Fix detected issues | The sooner the better :) | Use information from previous step to find TS errors and commit fixes. |\n| 3. Update `.betterer.results` file | Before merge at most | Open this [🔗 link to ci job](https://github.com/Evilweed/chatops-pr/runs/?check_suite_focus=true) and read instruction on how to update `.betterer.results` file |",
        "state": "CHANGES_REQUESTED",
        "html_url": "https://github.com/Evilweed/chatops-pr/pull/50#pullrequestreview-870824635",
        "pull_request_url": "https://api.github.com/repos/Evilweed/chatops-pr/pulls/50",
        "author_association": "NONE",
        "_links": {
            "html": {"href": "https://github.com/Evilweed/chatops-pr/pull/50#pullrequestreview-870824635"},
            "pull_request": {"href": "https://api.github.com/repos/Evilweed/chatops-pr/pulls/50"}
        },
        "submitted_at": "2022-02-02T16:42:55Z",
        "commit_id": "824c8a741f6da57da7af54aaf1aee749329d9ac8"
    }, {
        "id": 870830999,
        "node_id": "PRR_kwDOGhRBJM4z59OX",
        "user": {
            "login": "github-actions[bot]",
            "id": 41898282,
            "node_id": "MDM6Qm90NDE4OTgyODI=",
            "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/github-actions%5Bbot%5D",
            "html_url": "https://github.com/apps/github-actions",
            "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
            "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
            "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
            "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
            "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
            "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
            "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
            "type": "Bot",
            "site_admin": false
        },
        "body": "### 🤖 BOT: I\\'ve detected TypeScript quality changes!\nCI job that compiles this project with strict'er compilation detected changes. You have either fixed some TypeScript issues, or added new. You need to review those changes and either fix new TS issues, or accept new changes as ok which will store this state in file in repo.\n \n| Project |\n| ---- |\n| platform |\n \n| Action | When to do it | What, or details |\n| ---- | ----- | ----- |\n| 1. See detailed report | Now | Open this [🔗 link to ci job](https://github.com/Evilweed/chatops-pr/runs/?check_suite_focus=true) and check if there are some new TS errors you can fix. You can decide not to fix those issues - but keep in mind that we are trying to improve TS practices. |\n| 2. Fix detected issues | The sooner the better :) | Use information from previous step to find TS errors and commit fixes. |\n| 3. Update `.betterer.results` file | Before merge at most | Open this [🔗 link to ci job](https://github.com/Evilweed/chatops-pr/runs/?check_suite_focus=true) and read instruction on how to update `.betterer.results` file |",
        "state": "CHANGES_REQUESTED",
        "html_url": "https://github.com/Evilweed/chatops-pr/pull/50#pullrequestreview-870830999",
        "pull_request_url": "https://api.github.com/repos/Evilweed/chatops-pr/pulls/50",
        "author_association": "NONE",
        "_links": {
            "html": {"href": "https://github.com/Evilweed/chatops-pr/pull/50#pullrequestreview-870830999"},
            "pull_request": {"href": "https://api.github.com/repos/Evilweed/chatops-pr/pulls/50"}
        },
        "submitted_at": "2022-02-02T16:47:45Z",
        "commit_id": "824c8a741f6da57da7af54aaf1aee749329d9ac8"
    }, {
        "id": 870840980,
        "node_id": "PRR_kwDOGhRBJM4z5_qU",
        "user": {
            "login": "github-actions[bot]",
            "id": 41898282,
            "node_id": "MDM6Qm90NDE4OTgyODI=",
            "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/github-actions%5Bbot%5D",
            "html_url": "https://github.com/apps/github-actions",
            "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
            "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
            "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
            "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
            "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
            "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
            "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
            "type": "Bot",
            "site_admin": false
        },
        "body": "### 🤖 BOT: I\\'ve detected TypeScript quality changes!\nCI job that compiles this project with strict'er compilation detected changes. You have either fixed some TypeScript issues, or added new. You need to review those changes and either fix new TS issues, or accept new changes as ok which will store this state in file in repo.\n \n| Project |\n| ---- |\n| platform |\n \n| Action | When to do it | What, or details |\n| ---- | ----- | ----- |\n| 1. See detailed report | Now | Open this [🔗 link to ci job](https://github.com/Evilweed/chatops-pr/runs/?check_suite_focus=true) and check if there are some new TS errors you can fix. You can decide not to fix those issues - but keep in mind that we are trying to improve TS practices. |\n| 2. Fix detected issues | The sooner the better :) | Use information from previous step to find TS errors and commit fixes. |\n| 3. Update `.betterer.results` file | Before merge at most | Open this [🔗 link to ci job](https://github.com/Evilweed/chatops-pr/runs/?check_suite_focus=true) and read instruction on how to update `.betterer.results` file |",
        "state": "CHANGES_REQUESTED",
        "html_url": "https://github.com/Evilweed/chatops-pr/pull/50#pullrequestreview-870840980",
        "pull_request_url": "https://api.github.com/repos/Evilweed/chatops-pr/pulls/50",
        "author_association": "NONE",
        "_links": {
            "html": {"href": "https://github.com/Evilweed/chatops-pr/pull/50#pullrequestreview-870840980"},
            "pull_request": {"href": "https://api.github.com/repos/Evilweed/chatops-pr/pulls/50"}
        },
        "submitted_at": "2022-02-02T16:55:11Z",
        "commit_id": "490c195d37a283fdce5ad5663090461d6df1481a"
    }, {
        "id": 870852028,
        "node_id": "PRR_kwDOGhRBJM4z6CW8",
        "user": {
            "login": "github-actions[bot]",
            "id": 41898282,
            "node_id": "MDM6Qm90NDE4OTgyODI=",
            "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/github-actions%5Bbot%5D",
            "html_url": "https://github.com/apps/github-actions",
            "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
            "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
            "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
            "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
            "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
            "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
            "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
            "type": "Bot",
            "site_admin": false
        },
        "body": "### 🤖 BOT: I\\'ve detected TypeScript quality changes!\nCI job that compiles this project with strict'er compilation detected changes. You have either fixed some TypeScript issues, or added new. You need to review those changes and either fix new TS issues, or accept new changes as ok which will store this state in file in repo.\n \n| Project |\n| ---- |\n| platform |\n \n| Action | When to do it | What, or details |\n| ---- | ----- | ----- |\n| 1. See detailed report | Now | Open this [🔗 link to ci job](https://github.com/Evilweed/chatops-pr/runs/?check_suite_focus=true) and check if there are some new TS errors you can fix. You can decide not to fix those issues - but keep in mind that we are trying to improve TS practices. |\n| 2. Fix detected issues | The sooner the better :) | Use information from previous step to find TS errors and commit fixes. |\n| 3. Update `.betterer.results` file | Before merge at most | Open this [🔗 link to ci job](https://github.com/Evilweed/chatops-pr/runs/?check_suite_focus=true) and read instruction on how to update `.betterer.results` file |",
        "state": "CHANGES_REQUESTED",
        "html_url": "https://github.com/Evilweed/chatops-pr/pull/50#pullrequestreview-870852028",
        "pull_request_url": "https://api.github.com/repos/Evilweed/chatops-pr/pulls/50",
        "author_association": "NONE",
        "_links": {
            "html": {"href": "https://github.com/Evilweed/chatops-pr/pull/50#pullrequestreview-870852028"},
            "pull_request": {"href": "https://api.github.com/repos/Evilweed/chatops-pr/pulls/50"}
        },
        "submitted_at": "2022-02-02T17:03:15Z",
        "commit_id": "474ec46fac72594c9095b01f9ff2661529c7f232"
    }, {
        "id": 870861350,
        "node_id": "PRR_kwDOGhRBJM4z6Eom",
        "user": {
            "login": "github-actions[bot]",
            "id": 41898282,
            "node_id": "MDM6Qm90NDE4OTgyODI=",
            "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/github-actions%5Bbot%5D",
            "html_url": "https://github.com/apps/github-actions",
            "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
            "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
            "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
            "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
            "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
            "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
            "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
            "type": "Bot",
            "site_admin": false
        },
        "body": "### 🤖 BOT: I\\'ve detected TypeScript quality changes!\nCI job that compiles this project with strict'er compilation detected changes. You have either fixed some TypeScript issues, or added new. You need to review those changes and either fix new TS issues, or accept new changes as ok which will store this state in file in repo.\n \n| Project |\n| ---- |\n| platform |\n \n| Action | When to do it | What, or details |\n| ---- | ----- | ----- |\n| 1. See detailed report | Now | Open this [🔗 link to ci job](https://github.com/Evilweed/chatops-pr/runs/?check_suite_focus=true) and check if there are some new TS errors you can fix. You can decide not to fix those issues - but keep in mind that we are trying to improve TS practices. |\n| 2. Fix detected issues | The sooner the better :) | Use information from previous step to find TS errors and commit fixes. |\n| 3. Update `.betterer.results` file | Before merge at most | Open this [🔗 link to ci job](https://github.com/Evilweed/chatops-pr/runs/?check_suite_focus=true) and read instruction on how to update `.betterer.results` file |",
        "state": "CHANGES_REQUESTED",
        "html_url": "https://github.com/Evilweed/chatops-pr/pull/50#pullrequestreview-870861350",
        "pull_request_url": "https://api.github.com/repos/Evilweed/chatops-pr/pulls/50",
        "author_association": "NONE",
        "_links": {
            "html": {"href": "https://github.com/Evilweed/chatops-pr/pull/50#pullrequestreview-870861350"},
            "pull_request": {"href": "https://api.github.com/repos/Evilweed/chatops-pr/pulls/50"}
        },
        "submitted_at": "2022-02-02T17:10:30Z",
        "commit_id": "c81ca93f896ac827594efce458437e5321179654"
    }, {
        "id": 870869780,
        "node_id": "PRR_kwDOGhRBJM4z6GsU",
        "user": {
            "login": "github-actions[bot]",
            "id": 41898282,
            "node_id": "MDM6Qm90NDE4OTgyODI=",
            "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/github-actions%5Bbot%5D",
            "html_url": "https://github.com/apps/github-actions",
            "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
            "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
            "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
            "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
            "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
            "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
            "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
            "type": "Bot",
            "site_admin": false
        },
        "body": "### 🤖 BOT: I\\'ve detected TypeScript quality changes!\nCI job that compiles this project with strict'er compilation detected changes. You have either fixed some TypeScript issues, or added new. You need to review those changes and either fix new TS issues, or accept new changes as ok which will store this state in file in repo.\n \n| Project |\n| ---- |\n| platform |\n \n| Action | When to do it | What, or details |\n| ---- | ----- | ----- |\n| 1. See detailed report | Now | Open this [🔗 link to ci job](https://github.com/Evilweed/chatops-pr/runs/?check_suite_focus=true) and check if there are some new TS errors you can fix. You can decide not to fix those issues - but keep in mind that we are trying to improve TS practices. |\n| 2. Fix detected issues | The sooner the better :) | Use information from previous step to find TS errors and commit fixes. |\n| 3. Update `.betterer.results` file | Before merge at most | Open this [🔗 link to ci job](https://github.com/Evilweed/chatops-pr/runs/?check_suite_focus=true) and read instruction on how to update `.betterer.results` file |",
        "state": "CHANGES_REQUESTED",
        "html_url": "https://github.com/Evilweed/chatops-pr/pull/50#pullrequestreview-870869780",
        "pull_request_url": "https://api.github.com/repos/Evilweed/chatops-pr/pulls/50",
        "author_association": "NONE",
        "_links": {
            "html": {"href": "https://github.com/Evilweed/chatops-pr/pull/50#pullrequestreview-870869780"},
            "pull_request": {"href": "https://api.github.com/repos/Evilweed/chatops-pr/pulls/50"}
        },
        "submitted_at": "2022-02-02T17:17:07Z",
        "commit_id": "fcedb080ebcdea93fcf1fe8558ef61db4c0664bc"
    }, {
        "id": 870875780,
        "node_id": "PRR_kwDOGhRBJM4z6IKE",
        "user": {
            "login": "github-actions[bot]",
            "id": 41898282,
            "node_id": "MDM6Qm90NDE4OTgyODI=",
            "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/github-actions%5Bbot%5D",
            "html_url": "https://github.com/apps/github-actions",
            "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
            "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
            "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
            "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
            "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
            "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
            "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
            "type": "Bot",
            "site_admin": false
        },
        "body": "### 🤖 BOT: I\\'ve detected TypeScript quality changes!\nCI job that compiles this project with strict'er compilation detected changes. You have either fixed some TypeScript issues, or added new. You need to review those changes and either fix new TS issues, or accept new changes as ok which will store this state in file in repo.\n \n| Project |\n| ---- |\n| platform |\n \n| Action | When to do it | What, or details |\n| ---- | ----- | ----- |\n| 1. See detailed report | Now | Open this [🔗 link to ci job](https://github.com/Evilweed/chatops-pr/runs/?check_suite_focus=true) and check if there are some new TS errors you can fix. You can decide not to fix those issues - but keep in mind that we are trying to improve TS practices. |\n| 2. Fix detected issues | The sooner the better :) | Use information from previous step to find TS errors and commit fixes. |\n| 3. Update `.betterer.results` file | Before merge at most | Open this [🔗 link to ci job](https://github.com/Evilweed/chatops-pr/runs/?check_suite_focus=true) and read instruction on how to update `.betterer.results` file |",
        "state": "CHANGES_REQUESTED",
        "html_url": "https://github.com/Evilweed/chatops-pr/pull/50#pullrequestreview-870875780",
        "pull_request_url": "https://api.github.com/repos/Evilweed/chatops-pr/pulls/50",
        "author_association": "NONE",
        "_links": {
            "html": {"href": "https://github.com/Evilweed/chatops-pr/pull/50#pullrequestreview-870875780"},
            "pull_request": {"href": "https://api.github.com/repos/Evilweed/chatops-pr/pulls/50"}
        },
        "submitted_at": "2022-02-02T17:21:50Z",
        "commit_id": "5a4f1307191af6a1ddf841e95315f2506062ee15"
    }]
